CREATE DATABASE interview_prep;
USE interview_prep;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO users (name, email, password) VALUES
('Admin', 'admin@example.com', MD5('admin123'));

-- CREATE TABLE questions (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   job_role VARCHAR(100),
--   question TEXT
-- );
CREATE TABLE questions (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,            -- 'MCQ' or 'Mock'
    options TEXT,                         -- All options stored in one TEXT field (can be JSON or delimiter-separated)
    answer TEXT NOT NULL,                 -- Correct answer (e.g., 'A', 'B', etc.)
    job_role VARCHAR(100) NOT NULL,       -- e.g., 'AI Engineer', 'Web Developer'
    difficulty VARCHAR(50) NOT NULL       -- 'Easy', 'Medium', 'Hard'
);

CREATE TABLE user_results (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    total_marks INT(11) NOT NULL,
    correct_answers INT(11) NOT NULL,
    total_questions INT(11) NOT NULL,
    percentage FLOAT NOT NULL,
    test_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    transcript TEXT NOT NULL,
    wpm INT,
    filler_words INT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE usage_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    activity TEXT NOT NULL,
    activity_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table for uploaded resumes
CREATE TABLE resumes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_size INT NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for resume analysis results
CREATE TABLE resume_analysis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    resume_id INT NOT NULL,
    sections_found TEXT,
    score INT,
    suggestions TEXT,
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

-- Table for built resumes
CREATE TABLE built_resumes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    email VARCHAR(100),
    phone VARCHAR(20),
    education TEXT,
    experience TEXT,
    skills TEXT,
    projects TEXT,
    certifications TEXT,
    template_used VARCHAR(50),
    generated_file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Can you explain the difference between ID and class in CSS?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How would you optimize a website for performance?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Describe how the browser renders a web page.', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How do you manage state in a single-page application (SPA)?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What are some security concerns you consider when developing web applications?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Can you explain the difference between let, const, and var in JavaScript?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What’s the difference between responsive and adaptive design?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How would you handle browser compatibility issues?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Explain event delegation in JavaScript.', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How do you structure your CSS to make it scalable?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What are the advantages of using a CSS preprocessor?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What’s the difference between REST and GraphQL?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How does the virtual DOM work in React?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What is the difference between client-side and server-side rendering?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Describe your debugging process for web applications.', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What tools do you use for version control and deployment?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Can you explain the importance of semantic HTML?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How would you handle asynchronous operations in JavaScript?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What’s your approach to writing unit and integration tests for web apps?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How do you protect a web application from Cross-Site Scripting (XSS)?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What is the role of a build tool like Webpack?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('Explain the difference between cookies, localStorage, and sessionStorage.', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('How do you ensure accessibility in your web applications?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What is the critical rendering path in the browser?', 'mock', NULL, NULL, 'Web Developer', 'Mock'),
('What is lazy loading and when would you use it?', 'mock', NULL, NULL, 'Web Developer', 'Mock');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('What does HTML stand for?', 'mcq', 'A. Hyper Trainer Marking Language|B. Hyper Text Markup Language|C. Hyper Text Marketing Language|D. Hyper Text Marking Language', 'B', 'Web Developer', 'Easy'),
('Which HTML tag is used to create a hyperlink?', 'mcq', 'A. <link>|B. <a>|C. <href>|D. <hyperlink>', 'B', 'Web Developer', 'Easy'),
('Which property is used to change the background color in CSS?', 'mcq', 'A. color|B. bgcolor|C. background-color|D. background', 'C', 'Web Developer', 'Easy'),
('Inside which HTML element do we put the JavaScript?', 'mcq', 'A. <js>|B. <script>|C. <javascript>|D. <code>', 'B', 'Web Developer', 'Easy'),
('Which symbol is used for comments in JavaScript?', 'mcq', 'A. <!-- -->|B. ##|C. //|D. /* */', 'C', 'Web Developer', 'Easy'),
('Which tag is used to define an unordered list in HTML?', 'mcq', 'A. <ul>|B. <ol>|C. <li>|D. <list>', 'A', 'Web Developer', 'Easy'),
('What is the default position of an HTML element?', 'mcq', 'A. relative|B. fixed|C. absolute|D. static', 'D', 'Web Developer', 'Easy'),
('Which CSS property controls the text size?', 'mcq', 'A. font-style|B. text-size|C. font-size|D. text-style', 'C', 'Web Developer', 'Easy'),
('Which of the following is a JavaScript framework?', 'mcq', 'A. Django|B. Laravel|C. React|D. Flask', 'C', 'Web Developer', 'Easy'),
('What is the correct HTML element for inserting a line break?', 'mcq', 'A. <break>|B. <br>|C. <lb>|D. <line>', 'B', 'Web Developer', 'Easy'),
('What does CSS stand for?', 'mcq', 'A. Computer Style Sheets|B. Colorful Style Sheets|C. Creative Style Sheets|D. Cascading Style Sheets', 'D', 'Web Developer', 'Easy'),
('How do you make a numbered list in HTML?', 'mcq', 'A. <ul>|B. <ol>|C. <dl>|D. <list>', 'B', 'Web Developer', 'Easy'),
('Which of the following is used to define a JavaScript variable?', 'mcq', 'A. var|B. let|C. const|D. All of the above', 'D', 'Web Developer', 'Easy'),
('How do you create a function in JavaScript?', 'mcq', 'A. function:myFunction()|B. function myFunction()|C. function = myFunction()|D. create myFunction()', 'B', 'Web Developer', 'Easy'),
('How do you call a function named "myFunction"?', 'mcq', 'A. call myFunction|B. call function myFunction|C. myFunction()|D. myFunction;', 'C', 'Web Developer', 'Easy'),
('Which HTML element is used to display a scalar measurement within a range?', 'mcq', 'A. <gauge>|B. <meter>|C. <measure>|D. <scale>', 'B', 'Web Developer', 'Easy'),
('Which input type defines a slider control?', 'mcq', 'A. range|B. slider|C. scroll|D. number', 'A', 'Web Developer', 'Easy'),
('Which event occurs when the user clicks on an HTML element?', 'mcq', 'A. onmouseover|B. onchange|C. onmouseclick|D. onclick', 'D', 'Web Developer', 'Easy'),
('Which of the following tags is used to make text bold in HTML?', 'mcq', 'A. <b>|B. <bold>|C. <strong>|D. Both A and C', 'D', 'Web Developer', 'Easy'),
('Which CSS property is used to hide an element?', 'mcq', 'A. visibility: hidden|B. display: none|C. Both A and B|D. opacity: 0', 'C', 'Web Developer', 'Easy'),
('How do you create a comment in HTML?', 'mcq', 'A. // comment|B. /* comment */|C. <!-- comment -->|D. # comment', 'C', 'Web Developer', 'Easy'),
('Which tag is used to insert an image in HTML?', 'mcq', 'A. <img>|B. <image>|C. <src>|D. <pic>', 'A', 'Web Developer', 'Easy'),
('Which method is used to round a number to the nearest integer in JavaScript?', 'mcq', 'A. Math.round()|B. Math.floor()|C. Math.ceil()|D. Math.trim()', 'A', 'Web Developer', 'Easy'),
('What does DOM stand for?', 'mcq', 'A. Document Object Model|B. Data Object Model|C. Digital Output Management|D. Document Oriented Markup', 'A', 'Web Developer', 'Easy'),
('What is the correct way to refer to an external script called "app.js"?', 'mcq', 'A. <script href="app.js">|B. <script name="app.js">|C. <script src="app.js">|D. <script file="app.js">', 'C', 'Web Developer', 'Easy');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('What is the purpose of the "defer" attribute in a <script> tag?', 'mcq', 'A. It stops script execution|B. It executes the script after page load|C. It defers script execution until after the document is parsed|D. It preloads the script in memory', 'C', 'Web Developer', 'Medium'),
('Which of the following is not a valid HTTP method?', 'mcq', 'A. GET|B. POST|C. SEND|D. PUT', 'C', 'Web Developer', 'Medium'),
('In CSS, what does the "z-index" property control?', 'mcq', 'A. Opacity|B. Stacking order of elements|C. Element rotation|D. Element margin', 'B', 'Web Developer', 'Medium'),
('Which built-in method reverses the order of the elements of an array in JavaScript?', 'mcq', 'A. reverse()|B. sort()|C. changeOrder(order)|D. rearrange()', 'A', 'Web Developer', 'Medium'),
('What is the difference between == and === in JavaScript?', 'mcq', 'A. No difference|B. === compares values only|C. == checks type and value|D. === checks both type and value', 'D', 'Web Developer', 'Medium'),
('What will be the output of "typeof null" in JavaScript?', 'mcq', 'A. "null"|B. "object"|C. "undefined"|D. "boolean"', 'B', 'Web Developer', 'Medium'),
('Which of the following is used to apply styles to a single element with a specific ID in CSS?', 'mcq', 'A. .idname|B. #idname|C. idname|D. *idname', 'B', 'Web Developer', 'Medium'),
('What does the "this" keyword refer to in JavaScript?', 'mcq', 'A. The current function|B. The calling object|C. The previous function|D. The parent object', 'B', 'Web Developer', 'Medium'),
('Which API is used in HTML5 for storing data locally within the user’s browser?', 'mcq', 'A. WebSQL|B. LocalStorage|C. MySQL|D. WebServer', 'B', 'Web Developer', 'Medium'),
('Which of the following is not a semantic HTML5 element?', 'mcq', 'A. <article>|B. <footer>|C. <section>|D. <div>', 'D', 'Web Developer', 'Medium'),
('How can you prevent event bubbling in JavaScript?', 'mcq', 'A. stopPropagation()|B. preventDefault()|C. stopDefault()|D. disableEvent()', 'A', 'Web Developer', 'Medium'),
('What is the default display value of the <span> tag?', 'mcq', 'A. block|B. inline|C. flex|D. none', 'B', 'Web Developer', 'Medium'),
('Which method is used to add one or more elements to the end of an array?', 'mcq', 'A. push()|B. append()|C. insert()|D. add()', 'A', 'Web Developer', 'Medium'),
('Which CSS property is used to make a website responsive?', 'mcq', 'A. float|B. z-index|C. max-width|D. position', 'C', 'Web Developer', 'Medium'),
('Which of the following is true about cookies in JavaScript?', 'mcq', 'A. Cookies are accessible only from the server|B. Cookies expire only when browser closes|C. Cookies are stored in the client|D. Cookies are stored in the DOM', 'C', 'Web Developer', 'Medium'),
('Which pseudo-class is used to define a special style for the first line of a text?', 'mcq', 'A. :first|B. :line-first|C. :first-line|D. :start', 'C', 'Web Developer', 'Medium'),
('What is the purpose of the "viewport" meta tag in HTML?', 'mcq', 'A. To define browser caching|B. To support media queries|C. To make the site mobile-friendly|D. To improve SEO', 'C', 'Web Developer', 'Medium'),
('Which statement is true about "let" in JavaScript?', 'mcq', 'A. It has global scope|B. It is function-scoped|C. It allows block-scoped variables|D. It cannot be reassigned', 'C', 'Web Developer', 'Medium'),
('Which JavaScript method converts a JSON string into an object?', 'mcq', 'A. JSON.parse()|B. JSON.stringify()|C. JSON.toObject()|D. JSON.convert()', 'A', 'Web Developer', 'Medium'),
('How do you detect the client’s browser name in JavaScript?', 'mcq', 'A. navigator.appName|B. client.name|C. browser.name|D. location.browser', 'A', 'Web Developer', 'Medium'),
('Which tag defines a container for an external application or interactive content (a plug-in)?', 'mcq', 'A. <embed>|B. <object>|C. <applet>|D. All of the above', 'D', 'Web Developer', 'Medium'),
('How can you write a comment in CSS?', 'mcq', 'A. // comment|B. <!-- comment -->|C. /* comment */|D. # comment', 'C', 'Web Developer', 'Medium'),
('Which HTML5 element is used for drawing graphics via scripting?', 'mcq', 'A. <canvas>|B. <draw>|C. <graphics>|D. <svg>', 'A', 'Web Developer', 'Medium'),
('Which of the following is NOT a valid value for the display property?', 'mcq', 'A. inline|B. block|C. flex|D. visible', 'D', 'Web Developer', 'Medium'),
('What is the output of console.log(typeof []) in JavaScript?', 'mcq', 'A. "array"|B. "object"|C. "list"|D. "undefined"', 'B', 'Web Developer', 'Medium');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Which method is used to debounce a function in JavaScript?', 'mcq', 'A. throttle()|B. delay()|C. debounce()|D. setTimeout()', 'D', 'Web Developer', 'Hard'),
('What is the output of `0.1 + 0.2 === 0.3` in JavaScript?', 'mcq', 'A. true|B. false|C. undefined|D. throws error', 'B', 'Web Developer', 'Hard'),
('What is the shadow DOM in Web Components?', 'mcq', 'A. DOM inside iframe|B. DOM hidden using CSS|C. Encapsulated DOM|D. Transparent DOM', 'C', 'Web Developer', 'Hard'),
('What does CORS stand for?', 'mcq', 'A. Cross-Origin Resource Sharing|B. Common Origin Request Service|C. Current Origin Referrer Sharing|D. Cross-Origin Request Service', 'A', 'Web Developer', 'Hard'),
('What will be the result of the expression: `[] + []` in JavaScript?', 'mcq', 'A. 0|B. undefined|C. "" (empty string)|D. NaN', 'C', 'Web Developer', 'Hard'),
('What is a closure in JavaScript?', 'mcq', 'A. Function with only one argument|B. Nested function with access to outer scope|C. Anonymous function|D. Function that closes after execution', 'B', 'Web Developer', 'Hard'),
('Which CSS function is used to make color gradients?', 'mcq', 'A. rgba()|B. gradient()|C. linear-gradient()|D. fade()', 'C', 'Web Developer', 'Hard'),
('Which HTTP status code means "Request has been fulfilled and resulted in a new resource being created"?', 'mcq', 'A. 200|B. 201|C. 301|D. 204', 'B', 'Web Developer', 'Hard'),
('Which CSS property is used to create space between elements and their borders?', 'mcq', 'A. margin|B. padding|C. border-spacing|D. spacing', 'B', 'Web Developer', 'Hard'),
('What is the correct way to write a media query targeting screen widths greater than 768px?', 'mcq', 'A. @media screen and (min-width: 768px)|B. @media screen (width >= 768px)|C. @media screen and width > 768px|D. @media screen[min-width:768px]', 'A', 'Web Developer', 'Hard'),
('Which method is used to clone an object in JavaScript without references?', 'mcq', 'A. Object.copy()|B. JSON.parse(JSON.stringify(obj))|C. obj.clone()|D. Object.assign({}, obj)', 'B', 'Web Developer', 'Hard'),
('Which attribute can be used in HTML5 to validate user input?', 'mcq', 'A. validate|B. pattern|C. match|D. input-type', 'B', 'Web Developer', 'Hard'),
('Which CSS property determines the stacking order of elements?', 'mcq', 'A. position|B. layer|C. index|D. z-index', 'D', 'Web Developer', 'Hard'),
('Which JavaScript method returns the characters in a string beginning at the specified location through the specified number of characters?', 'mcq', 'A. substr()|B. substring()|C. slice()|D. charAt()', 'A', 'Web Developer', 'Hard'),
('What does "use strict" do in JavaScript?', 'mcq', 'A. Makes code secure|B. Prevents undefined variables|C. Enables ES6|D. Prevents hoisting', 'B', 'Web Developer', 'Hard'),
('Which feature of ES6 allows spreading of iterable objects into individual elements?', 'mcq', 'A. Destructuring|B. Spread operator|C. Rest parameters|D. For...of loop', 'B', 'Web Developer', 'Hard'),
('What is a service worker?', 'mcq', 'A. JavaScript function to handle APIs|B. Worker that handles async UI|C. Script that runs in the background and handles caching|D. HTML worker element', 'C', 'Web Developer', 'Hard'),
('What does the CSS property "object-fit: cover" do?', 'mcq', 'A. Resizes image to fit box keeping aspect ratio|B. Crops image|C. Fills image box without resizing|D. Stretches image to fill box', 'A', 'Web Developer', 'Hard'),
('How do you define a custom HTML element?', 'mcq', 'A. document.define()|B. customElements.define()|C. element.define()|D. defineCustomElement()', 'B', 'Web Developer', 'Hard'),
('What is the purpose of the `rel="noopener noreferrer"` attribute on a link?', 'mcq', 'A. Opens link in new window|B. Secures the new tab from accessing window.opener|C. Optimizes loading|D. Preloads page', 'B', 'Web Developer', 'Hard'),
('What does the term "progressive enhancement" mean?', 'mcq', 'A. Loading page progressively|B. Enhancing UI step by step|C. Building base functionality first then enhancing|D. Lazy loading', 'C', 'Web Developer', 'Hard'),
('What is "hoisting" in JavaScript?', 'mcq', 'A. Raising errors|B. Pulling DOM elements|C. Moving declarations to top|D. Variable hiding', 'C', 'Web Developer', 'Hard'),
('Which of the following is true about the async/await feature in JavaScript?', 'mcq', 'A. Makes function run in parallel|B. Blocks execution|C. Makes asynchronous code look synchronous|D. Slows down performance', 'C', 'Web Developer', 'Hard'),
('Which JavaScript object allows working with dates and times?', 'mcq', 'A. Time|B. Clock|C. Calendar|D. Date', 'D', 'Web Developer', 'Hard'),
('What does the Content Security Policy (CSP) do?', 'mcq', 'A. Allows third-party scripts|B. Prevents XSS by restricting resources|C. Logs browser errors|D. Encrypts page data', 'B', 'Web Developer', 'Hard');

-- for data analyst
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('What are the key responsibilities of a Data Analyst?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Can you explain the difference between data mining and data analysis?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What are the common data cleaning techniques you use?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Describe a time you identified a business problem and how data helped you solve it.', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('How do you handle missing or inconsistent data in a dataset?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What is the difference between inner join and outer join in SQL?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('How do you decide which visualization to use for your data?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Can you explain what a p-value is and its significance in data analysis?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What tools and software do you prefer for data analysis?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What’s your process for analyzing a large dataset?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Explain the importance of data validation.', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What is the role of a data analyst in a business decision-making process?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What’s the difference between structured and unstructured data?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('How would you explain regression analysis to a non-technical stakeholder?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Can you describe a project where your analysis directly impacted a company decision?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What is data normalization and why is it important?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('How do you ensure the accuracy and integrity of your data?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What’s the difference between a clustered and non-clustered index in SQL?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Describe how you would handle outliers in your dataset.', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What is A/B testing and when would you use it?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('How do you prioritize tasks when you’re handling multiple projects?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What’s the difference between correlation and causation?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Explain the concept of data warehousing.', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('Have you worked with APIs to gather external data? How?', 'mock', NULL, NULL, 'Data Analyst', 'Mock'),
('What are some key metrics you track for a marketing campaign analysis?', 'mock', NULL, NULL, 'Data Analyst', 'Mock');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('What does SQL stand for?', 'mcq', 'A. Structured Question Language|B. Sequential Query Language|C. Structured Query Language|D. Simple Query Language', 'C', 'Data Analyst', 'Easy'),
('Which of these is a Python data visualization library?', 'mcq', 'A. NumPy|B. Pandas|C. Matplotlib|D. Scikit-learn', 'C', 'Data Analyst', 'Easy'),
('Which function is used to find the average in Excel?', 'mcq', 'A. ADD|B. MEAN|C. AVG|D. AVERAGE', 'D', 'Data Analyst', 'Easy'),
('Which of the following is used to store tabular data in Python?', 'mcq', 'A. NumPy array|B. DataFrame|C. List|D. Dictionary', 'B', 'Data Analyst', 'Easy'),
('Which command is used to retrieve data from a database?', 'mcq', 'A. GET|B. FETCH|C. SELECT|D. READ', 'C', 'Data Analyst', 'Easy'),
('What does CSV stand for?', 'mcq', 'A. Comma Shared Values|B. Column-Separated Values|C. Comma Separated Values|D. Common Spreadsheet Version', 'C', 'Data Analyst', 'Easy'),
('Which of these is a measure of central tendency?', 'mcq', 'A. Mean|B. Standard deviation|C. Variance|D. Quartile', 'A', 'Data Analyst', 'Easy'),
('Which Python package is commonly used for data manipulation?', 'mcq', 'A. Matplotlib|B. NumPy|C. Pandas|D. Seaborn', 'C', 'Data Analyst', 'Easy'),
('Which SQL clause is used to filter results?', 'mcq', 'A. ORDER BY|B. WHERE|C. GROUP BY|D. HAVING', 'B', 'Data Analyst', 'Easy'),
('What type of chart is best for showing proportions?', 'mcq', 'A. Bar chart|B. Line chart|C. Pie chart|D. Scatter plot', 'C', 'Data Analyst', 'Easy'),
('Which file format is NOT typically used for data analysis?', 'mcq', 'A. .csv|B. .xlsx|C. .mp3|D. .json', 'C', 'Data Analyst', 'Easy'),
('Which Excel function is used to count numeric values?', 'mcq', 'A. COUNT|B. COUNTA|C. SUM|D. AVERAGE', 'A', 'Data Analyst', 'Easy'),
('What is the output of len([10, 20, 30]) in Python?', 'mcq', 'A. 2|B. 3|C. 4|D. Error', 'B', 'Data Analyst', 'Easy'),
('Which keyword is used in SQL to sort records?', 'mcq', 'A. ORDER BY|B. SORT BY|C. ARRANGE|D. ALIGN', 'A', 'Data Analyst', 'Easy'),
('Which of these is a relational database?', 'mcq', 'A. MongoDB|B. Excel|C. MySQL|D. Redis', 'C', 'Data Analyst', 'Easy'),
('Which Python function is used to display the first 5 rows of a DataFrame?', 'mcq', 'A. top()|B. start()|C. head()|D. first()', 'C', 'Data Analyst', 'Easy'),
('What does NULL represent in SQL?', 'mcq', 'A. 0|B. Empty string|C. Unknown or missing value|D. False', 'C', 'Data Analyst', 'Easy'),
('What does the COUNT() function do in SQL?', 'mcq', 'A. Sums the values|B. Finds maximum|C. Counts records|D. Returns distinct values', 'C', 'Data Analyst', 'Easy'),
('Which of these is a type of data?', 'mcq', 'A. Pie|B. Scatter|C. Numerical|D. Row', 'C', 'Data Analyst', 'Easy'),
('Which tool is primarily used for spreadsheets?', 'mcq', 'A. Tableau|B. Excel|C. MySQL|D. R', 'B', 'Data Analyst', 'Easy'),
('What symbol is used for comments in Python?', 'mcq', 'A. //@|B. #|C. <!--|D. --', 'B', 'Data Analyst', 'Easy'),
('Which method shows summary statistics in Pandas?', 'mcq', 'A. summary()|B. overview()|C. describe()|D. stats()', 'C', 'Data Analyst', 'Easy'),
('What is the main use of Tableau?', 'mcq', 'A. Writing SQL queries|B. Data cleaning|C. Data visualization|D. Running code', 'C', 'Data Analyst', 'Easy'),
('Which command in Python shows column names of a DataFrame?', 'mcq', 'A. columns()|B. df.column_names|C. df.columns|D. get_columns()', 'C', 'Data Analyst', 'Easy'),
('Which chart is best for time series data?', 'mcq', 'A. Pie chart|B. Line chart|C. Bar chart|D. Histogram', 'B', 'Data Analyst', 'Easy');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Which SQL clause is used to group records that have the same values?', 'mcq', 'A. WHERE|B. ORDER BY|C. GROUP BY|D. HAVING', 'C', 'Data Analyst', 'Medium'),
('In Python, what does df[df[\"column\"] > 10] return?', 'mcq', 'A. A sorted DataFrame|B. A DataFrame with nulls|C. A filtered DataFrame|D. A new column', 'C', 'Data Analyst', 'Medium'),
('Which of the following is a method to merge two DataFrames in Pandas?', 'mcq', 'A. append()|B. connect()|C. combine()|D. merge()', 'D', 'Data Analyst', 'Medium'),
('What is the result of a LEFT JOIN in SQL?', 'mcq', 'A. Only matching rows from both tables|B. All rows from the left table and matching rows from the right|C. All rows from the right table|D. Non-matching rows only', 'B', 'Data Analyst', 'Medium'),
('Which chart type is best suited for correlation analysis?', 'mcq', 'A. Line chart|B. Pie chart|C. Scatter plot|D. Area chart', 'C', 'Data Analyst', 'Medium'),
('Which statistical test is used to compare the means of two groups?', 'mcq', 'A. T-test|B. ANOVA|C. Chi-square|D. Regression', 'A', 'Data Analyst', 'Medium'),
('Which SQL function returns the number of unique values?', 'mcq', 'A. COUNT(*)|B. COUNT(DISTINCT column)|C. SUM(column)|D. MAX(column)', 'B', 'Data Analyst', 'Medium'),
('What does NaN stand for in data analysis?', 'mcq', 'A. Not a Number|B. Null and None|C. No assigned Name|D. Name as Number', 'A', 'Data Analyst', 'Medium'),
('What is a primary key?', 'mcq', 'A. A duplicate column|B. A foreign reference|C. A unique identifier|D. A data type', 'C', 'Data Analyst', 'Medium'),
('Which method can you use to fill missing values in a DataFrame?', 'mcq', 'A. dropna()|B. fillna()|C. nafill()|D. fillnull()', 'B', 'Data Analyst', 'Medium'),
('Which of these is a data wrangling process?', 'mcq', 'A. Data deletion|B. Data mining|C. Data cleaning|D. Data encryption', 'C', 'Data Analyst', 'Medium'),
('Which type of join returns all records when there is a match in either left or right table?', 'mcq', 'A. INNER JOIN|B. OUTER JOIN|C. LEFT JOIN|D. CROSS JOIN', 'B', 'Data Analyst', 'Medium'),
('In SQL, which clause is used after GROUP BY to filter grouped rows?', 'mcq', 'A. WHERE|B. ORDER BY|C. HAVING|D. FILTER BY', 'C', 'Data Analyst', 'Medium'),
('What is the purpose of one-hot encoding?', 'mcq', 'A. Reduce dataset size|B. Handle missing data|C. Convert categorical data into numeric|D. Normalize data', 'C', 'Data Analyst', 'Medium'),
('Which Python method is used to detect missing values in a DataFrame?', 'mcq', 'A. isnull()|B. checknull()|C. findna()|D. isempty()', 'A', 'Data Analyst', 'Medium'),
('Which metric is best for measuring data spread?', 'mcq', 'A. Mean|B. Median|C. Standard Deviation|D. Mode', 'C', 'Data Analyst', 'Medium'),
('Which operator in SQL is used to check for a value in a list?', 'mcq', 'A. LIKE|B. BETWEEN|C. IN|D. MATCH', 'C', 'Data Analyst', 'Medium'),
('Which tool is most commonly used for ETL tasks?', 'mcq', 'A. Tableau|B. Power BI|C. Apache Airflow|D. Excel', 'C', 'Data Analyst', 'Medium'),
('Which command gives the number of rows and columns in Pandas?', 'mcq', 'A. df.length|B. df.shape|C. df.size|D. df.count', 'B', 'Data Analyst', 'Medium'),
('What does a p-value indicate in hypothesis testing?', 'mcq', 'A. Sample size|B. Likelihood of null hypothesis|C. Degree of correlation|D. Type of variable', 'B', 'Data Analyst', 'Medium'),
('What is the purpose of normalization in data processing?', 'mcq', 'A. To delete duplicate data|B. To improve security|C. To scale features to a common range|D. To sort the data', 'C', 'Data Analyst', 'Medium'),
('Which method is used to join DataFrames side-by-side in Pandas?', 'mcq', 'A. pd.concat(axis=1)|B. pd.stack()|C. pd.append()|D. pd.merge()', 'A', 'Data Analyst', 'Medium'),
('Which library in Python is widely used for statistical analysis?', 'mcq', 'A. Seaborn|B. SciPy|C. Matplotlib|D. NumPy', 'B', 'Data Analyst', 'Medium'),
('Which SQL keyword is used to eliminate duplicate records?', 'mcq', 'A. DELETE|B. REMOVE|C. DISTINCT|D. UNIQUE', 'C', 'Data Analyst', 'Medium'),
('Which Python visualization library is based on matplotlib and provides a higher-level interface?', 'mcq', 'A. Pandas|B. Plotly|C. Seaborn|D. NumPy', 'C', 'Data Analyst', 'Medium');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Which algorithm is used in dimensionality reduction techniques like t-SNE?', 'mcq', 'A. Logistic Regression|B. Decision Tree|C. K-Means|D. Stochastic Neighbor Embedding', 'D', 'Data Analyst', 'Hard'),
('In time series forecasting, what does ARIMA stand for?', 'mcq', 'A. Automated Regressive Integrated Model Analysis|B. Autoregressive Integrated Moving Average|C. Average Regression Integrated Matrix Algorithm|D. Augmented Regressive Interval Mean Analysis', 'B', 'Data Analyst', 'Hard'),
('Which statistical test is suitable for checking normality of data?', 'mcq', 'A. Chi-Square Test|B. Kolmogorov-Smirnov Test|C. Z-Test|D. ANOVA', 'B', 'Data Analyst', 'Hard'),
('What does PCA do to features in a dataset?', 'mcq', 'A. Removes all outliers|B. Converts numerical to categorical|C. Transforms correlated features to uncorrelated|D. Balances the dataset', 'C', 'Data Analyst', 'Hard'),
('Which SQL window function is used to calculate cumulative totals?', 'mcq', 'A. RANK()|B. COUNT()|C. SUM() OVER()|D. GROUP BY', 'C', 'Data Analyst', 'Hard'),
('Which Pandas function can be used to pivot a table based on multiple columns?', 'mcq', 'A. melt()|B. groupby()|C. pivot_table()|D. unstack()', 'C', 'Data Analyst', 'Hard'),
('Which Python module is best for working with date and time data in Pandas?', 'mcq', 'A. pytz|B. time|C. calendar|D. datetime', 'D', 'Data Analyst', 'Hard'),
('Which SQL clause is used with OVER() to create partitions for window functions?', 'mcq', 'A. SPLIT BY|B. DIVIDE BY|C. PARTITION BY|D. SECTION BY', 'C', 'Data Analyst', 'Hard'),
('In data science, what is heteroscedasticity?', 'mcq', 'A. Constant variance across data|B. No correlation|C. Increasing variance over time|D. Equal mean values', 'C', 'Data Analyst', 'Hard'),
('Which visualization is ideal for showing high-dimensional data?', 'mcq', 'A. Line chart|B. Bar chart|C. Heatmap|D. Parallel coordinates plot', 'D', 'Data Analyst', 'Hard'),
('Which Python function returns eigenvalues of a matrix?', 'mcq', 'A. numpy.linalg.eigvals()|B. numpy.eigen()|C. numpy.matrix.eig()|D. numpy.linalg.matrix()', 'A', 'Data Analyst', 'Hard'),
('Which technique is used to handle imbalanced datasets?', 'mcq', 'A. K-Fold Validation|B. Data Augmentation|C. SMOTE|D. Normalization', 'C', 'Data Analyst', 'Hard'),
('What is the purpose of lag features in time series?', 'mcq', 'A. Reduce memory|B. Add randomness|C. Use past values for prediction|D. Convert time zone', 'C', 'Data Analyst', 'Hard'),
('Which method is used in Pandas to shift data forward or backward?', 'mcq', 'A. roll()|B. move()|C. shift()|D. offset()', 'C', 'Data Analyst', 'Hard'),
('Which technique in statistics helps detect multicollinearity?', 'mcq', 'A. Z-Score|B. VIF (Variance Inflation Factor)|C. Correlation Matrix|D. ANOVA', 'B', 'Data Analyst', 'Hard'),
('Which function finds the rolling average in Pandas?', 'mcq', 'A. moving_mean()|B. roll_mean()|C. rolling().mean()|D. avg_roll()', 'C', 'Data Analyst', 'Hard'),
('Which test is used for feature selection in categorical data?', 'mcq', 'A. T-test|B. Chi-Square|C. ANOVA|D. Z-test', 'B', 'Data Analyst', 'Hard'),
('Which Python library can be used for anomaly detection?', 'mcq', 'A. TensorFlow|B. PyCaret|C. Scikit-learn|D. PyOD', 'D', 'Data Analyst', 'Hard'),
('What is the key difference between INNER JOIN and CROSS JOIN?', 'mcq', 'A. INNER JOIN creates Cartesian product|B. CROSS JOIN filters rows|C. CROSS JOIN creates Cartesian product|D. INNER JOIN returns all combinations', 'C', 'Data Analyst', 'Hard'),
('Which concept is applied when transforming skewed data?', 'mcq', 'A. Feature Scaling|B. Log Transformation|C. Data Sampling|D. Data Wrangling', 'B', 'Data Analyst', 'Hard'),
('What does the term “curse of dimensionality” refer to?', 'mcq', 'A. Data corruption in large datasets|B. Loss of data|C. Increased complexity with more features|D. Decreased correlation with more rows', 'C', 'Data Analyst', 'Hard'),
('Which statistical method helps reduce overfitting in regression?', 'mcq', 'A. Linear Regression|B. Ridge Regression|C. Logistic Regression|D. Decision Tree', 'B', 'Data Analyst', 'Hard'),
('Which Pandas method can be used to resample time series data?', 'mcq', 'A. groupby()|B. timesample()|C. resample()|D. timechunk()', 'C', 'Data Analyst', 'Hard'),
('Which technique is NOT used for outlier detection?', 'mcq', 'A. Z-Score|B. Box Plot|C. K-Means|D. Histogram', 'D', 'Data Analyst', 'Hard'),
('Which database indexing method speeds up range queries?', 'mcq', 'A. Hash Indexing|B. Tree Indexing|C. Linear Scan|D. Full Table Scan', 'B', 'Data Analyst', 'Hard');

-- for AI Engineer
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Explain the difference between supervised and unsupervised learning with examples.', 'mock', '', '', 'AI Engineer', 'Mock'),
('How do you select important features in a dataset before training an AI model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Can you explain how backpropagation works in a neural network?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What are some techniques to prevent overfitting in a deep learning model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How would you approach designing an AI model for fraud detection?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What are the key differences between CNNs and RNNs?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How do you choose the right evaluation metric for your model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Can you explain the vanishing gradient problem?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What are generative models and how are they used?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Explain how attention mechanisms work in NLP models.', 'mock', '', '', 'AI Engineer', 'Mock'),
('What is transfer learning and when would you use it?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How would you detect bias in an AI model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Explain the architecture of a Transformer model.', 'mock', '', '', 'AI Engineer', 'Mock'),
('How would you deploy a deep learning model into production?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What are the challenges in training a GAN?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How do you interpret the results of a confusion matrix?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What is the difference between bagging and boosting?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How would you tune hyperparameters for a deep learning model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('What are embeddings in NLP and how are they created?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Describe a project where you used AI to solve a real-world problem.', 'mock', '', '', 'AI Engineer', 'Mock'),
('What is the role of activation functions in neural networks?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How would you evaluate the fairness of an AI model?', 'mock', '', '', 'AI Engineer', 'Mock'),
('Explain reinforcement learning with an example.', 'mock', '', '', 'AI Engineer', 'Mock'),
('What is the difference between precision and recall? When do you prioritize one over the other?', 'mock', '', '', 'AI Engineer', 'Mock'),
('How do you handle imbalanced datasets?', 'mock', '', '', 'AI Engineer', 'Mock');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('What does AI stand for?', 'mcq', 'A. Automated Interface|B. Artificial Intelligence|C. Analytical Integration|D. Algorithmic Inference', 'B', 'AI Engineer', 'Easy'),
('Which language is most commonly used for AI development?', 'mcq', 'A. Python|B. JavaScript|C. HTML|D. SQL', 'A', 'AI Engineer', 'Easy'),
('What is the purpose of a training dataset in machine learning?', 'mcq', 'A. To test models|B. To update models|C. To build models|D. To deploy models', 'C', 'AI Engineer', 'Easy'),
('Which of the following is a supervised learning algorithm?', 'mcq', 'A. K-Means|B. PCA|C. Decision Tree|D. Apriori', 'C', 'AI Engineer', 'Easy'),
('Which library is used in Python for deep learning?', 'mcq', 'A. NumPy|B. Pandas|C. TensorFlow|D. Matplotlib', 'C', 'AI Engineer', 'Easy'),
('Which algorithm is used for classification problems?', 'mcq', 'A. K-Means|B. Linear Regression|C. Logistic Regression|D. DBSCAN', 'C', 'AI Engineer', 'Easy'),
('What does NLP stand for?', 'mcq', 'A. Neural Language Platform|B. Natural Learning Program|C. Natural Language Processing|D. Neural Logic Processing', 'C', 'AI Engineer', 'Easy'),
('Which activation function outputs between 0 and 1?', 'mcq', 'A. Tanh|B. ReLU|C. Sigmoid|D. Softmax', 'C', 'AI Engineer', 'Easy'),
('Which of the following is NOT a type of machine learning?', 'mcq', 'A. Supervised|B. Reinforcement|C. Unsupervised|D. Algorithmic', 'D', 'AI Engineer', 'Easy'),
('Which technique reduces the number of features in a dataset?', 'mcq', 'A. Overfitting|B. PCA|C. Regression|D. Classification', 'B', 'AI Engineer', 'Easy'),
('Which one is a Python library for numerical computing?', 'mcq', 'A. TensorFlow|B. NumPy|C. Matplotlib|D. Keras', 'B', 'AI Engineer', 'Easy'),
('Which type of learning uses rewards and penalties?', 'mcq', 'A. Supervised Learning|B. Reinforcement Learning|C. Unsupervised Learning|D. Deep Learning', 'B', 'AI Engineer', 'Easy'),
('Which tool is used for data visualization in Python?', 'mcq', 'A. Seaborn|B. Pandas|C. NumPy|D. OpenCV', 'A', 'AI Engineer', 'Easy'),
('Which neural network is best suited for image data?', 'mcq', 'A. CNN|B. RNN|C. LSTM|D. GAN', 'A', 'AI Engineer', 'Easy'),
('What is overfitting in ML?', 'mcq', 'A. Model performs poorly on all data|B. Model performs well on test data only|C. Model memorizes training data|D. Model has high bias', 'C', 'AI Engineer', 'Easy'),
('Which metric is commonly used to evaluate classification models?', 'mcq', 'A. MAE|B. RMSE|C. Accuracy|D. SSE', 'C', 'AI Engineer', 'Easy'),
('Which of the following is a loss function for regression?', 'mcq', 'A. Cross Entropy|B. Binary Loss|C. Mean Squared Error|D. Hinge Loss', 'C', 'AI Engineer', 'Easy'),
('Which of the following is NOT a deep learning framework?', 'mcq', 'A. PyTorch|B. TensorFlow|C. Keras|D. Pandas', 'D', 'AI Engineer', 'Easy'),
('What is the full form of RNN?', 'mcq', 'A. Recursive Neural Network|B. Random Neural Network|C. Recurrent Neural Network|D. Real Neural Network', 'C', 'AI Engineer', 'Easy'),
('Which of the following is used to handle missing data?', 'mcq', 'A. Dropna|B. Fillna|C. Both A and B|D. None', 'C', 'AI Engineer', 'Easy'),
('Which of the following is a feature scaling technique?', 'mcq', 'A. PCA|B. Normalization|C. Regression|D. Tokenization', 'B', 'AI Engineer', 'Easy'),
('What is the role of an optimizer in deep learning?', 'mcq', 'A. Enhance accuracy|B. Reduce loss|C. Increase size|D. Boost speed', 'B', 'AI Engineer', 'Easy'),
('Which is used to train a model?', 'mcq', 'A. test data|B. validation data|C. training data|D. production data', 'C', 'AI Engineer', 'Easy'),
('Which method splits data into training and testing sets?', 'mcq', 'A. model_split()|B. train_test_split()|C. data_split()|D. split_dataset()', 'B', 'AI Engineer', 'Easy'),
('Which of the following is used for dimensionality reduction?', 'mcq', 'A. Normalization|B. Standardization|C. PCA|D. Encoding', 'C', 'AI Engineer', 'Easy');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Which algorithm is used to reduce overfitting in decision trees?', 'mcq', 'A. Pruning|B. Splitting|C. Binarization|D. Clustering', 'A', 'AI Engineer', 'Medium'),
('Which library provides pre-trained models in PyTorch?', 'mcq', 'A. TorchVision|B. NumPy|C. Seaborn|D. Scikit-learn', 'A', 'AI Engineer', 'Medium'),
('In NLP, what is the purpose of lemmatization?', 'mcq', 'A. Compress data|B. Convert words to base form|C. Create summaries|D. Remove punctuation', 'B', 'AI Engineer', 'Medium'),
('What does LSTM stand for?', 'mcq', 'A. Large Scale Transformer Model|B. Long Short-Term Memory|C. Linear Softmax Training Mechanism|D. Least Squared Term Model', 'B', 'AI Engineer', 'Medium'),
('What is the vanishing gradient problem?', 'mcq', 'A. Gradients explode rapidly|B. Gradients become zero|C. Gradient never changes|D. Model accuracy never improves', 'B', 'AI Engineer', 'Medium'),
('Which method is used to detect overfitting during training?', 'mcq', 'A. Dropout|B. Regularization|C. Cross-validation|D. Normalization', 'C', 'AI Engineer', 'Medium'),
('Which layer in CNN performs feature extraction?', 'mcq', 'A. Dense|B. Dropout|C. Convolutional|D. ReLU', 'C', 'AI Engineer', 'Medium'),
('Which attention mechanism is used in Transformers?', 'mcq', 'A. Multi-head Attention|B. Sigmoid Attention|C. Pooling Attention|D. Recursive Attention', 'A', 'AI Engineer', 'Medium'),
('Which evaluation metric is best for imbalanced datasets?', 'mcq', 'A. Accuracy|B. Precision|C. F1-Score|D. RMSE', 'C', 'AI Engineer', 'Medium'),
('Which is used to visualize high-dimensional data?', 'mcq', 'A. t-SNE|B. Linear Regression|C. Bar Chart|D. Confusion Matrix', 'A', 'AI Engineer', 'Medium'),
('Which method can be used for text classification?', 'mcq', 'A. Naive Bayes|B. K-Means|C. KNN|D. PCA', 'A', 'AI Engineer', 'Medium'),
('What is the primary function of an embedding layer in NLP?', 'mcq', 'A. Convert text into images|B. Visualize datasets|C. Reduce text to numerical vectors|D. Translate languages', 'C', 'AI Engineer', 'Medium'),
('Which method is used to combine weak learners into strong learners?', 'mcq', 'A. Pruning|B. Bootstrapping|C. Bagging|D. Boosting', 'D', 'AI Engineer', 'Medium'),
('Which component in a neural network controls learning?', 'mcq', 'A. Epoch|B. Batch|C. Learning Rate|D. Loss Function', 'C', 'AI Engineer', 'Medium'),
('What does ReLU return for negative values?', 'mcq', 'A. 0|B. 1|C. -1|D. Same value', 'A', 'AI Engineer', 'Medium'),
('Which function is suitable for multiclass classification?', 'mcq', 'A. ReLU|B. Softmax|C. Sigmoid|D. Tanh', 'B', 'AI Engineer', 'Medium'),
('What is the purpose of a validation set?', 'mcq', 'A. Test the final model|B. Train the model|C. Tune model parameters|D. Store predictions', 'C', 'AI Engineer', 'Medium'),
('Which algorithm is best suited for sequence data?', 'mcq', 'A. CNN|B. RNN|C. KNN|D. SVM', 'B', 'AI Engineer', 'Medium'),
('Which optimizer adapts the learning rate based on past gradients?', 'mcq', 'A. SGD|B. Adam|C. RMSprop|D. Momentum', 'B', 'AI Engineer', 'Medium'),
('Which loss function is typically used for binary classification?', 'mcq', 'A. Hinge Loss|B. Cross-Entropy|C. MSE|D. MAE', 'B', 'AI Engineer', 'Medium'),
('What is the typical range of the tanh activation function?', 'mcq', 'A. 0 to 1|B. -1 to 1|C. -∞ to ∞|D. 0 to ∞', 'B', 'AI Engineer', 'Medium'),
('Which of the following is a generative model?', 'mcq', 'A. SVM|B. CNN|C. GAN|D. RNN', 'C', 'AI Engineer', 'Medium'),
('Which algorithm is useful for topic modeling?', 'mcq', 'A. Naive Bayes|B. LDA|C. PCA|D. SVM', 'B', 'AI Engineer', 'Medium'),
('Which function penalizes large weights in neural networks?', 'mcq', 'A. ReLU|B. Regularization|C. Dropout|D. Normalization', 'B', 'AI Engineer', 'Medium'),
('Which of the following is true about Batch Normalization?', 'mcq', 'A. Prevents overfitting|B. Speeds up training|C. Removes outliers|D. Converts categorical data', 'B', 'AI Engineer', 'Medium');
INSERT INTO questions (question, type, options, answer, job_role, difficulty) VALUES
('Which technique is used for transfer learning in NLP?', 'mcq', 'A. LDA|B. Word2Vec|C. BERT|D. KNN', 'C', 'AI Engineer', 'Hard'),
('What does gradient clipping help prevent?', 'mcq', 'A. Overfitting|B. Vanishing gradient|C. Exploding gradient|D. Underfitting', 'C', 'AI Engineer', 'Hard'),
('Which is true about the Transformer architecture?', 'mcq', 'A. Uses RNNs|B. Requires sequence alignment|C. Uses positional encoding|D. Requires convolution layers', 'C', 'AI Engineer', 'Hard'),
('What is the output of the softmax function?', 'mcq', 'A. Binary output|B. Probability distribution|C. One-hot encoding|D. Logarithmic output', 'B', 'AI Engineer', 'Hard'),
('Which of the following is not part of the encoder in a Transformer?', 'mcq', 'A. Self-attention|B. Feed-forward|C. Layer norm|D. Decoder block', 'D', 'AI Engineer', 'Hard'),
('What is a major challenge in training GANs?', 'mcq', 'A. Overfitting|B. Vanishing gradient|C. Mode collapse|D. Low accuracy', 'C', 'AI Engineer', 'Hard'),
('Which technique helps prevent mode collapse in GANs?', 'mcq', 'A. Dropout|B. Weight decay|C. Feature matching|D. Batch normalization', 'C', 'AI Engineer', 'Hard'),
('Which concept allows transformers to process entire sequences in parallel?', 'mcq', 'A. Self-attention|B. RNN loops|C. Feed-forward layers|D. Pooling', 'A', 'AI Engineer', 'Hard'),
('Which regularization technique randomly disables neurons?', 'mcq', 'A. L1 Regularization|B. Dropout|C. Batch Norm|D. Data Augmentation', 'B', 'AI Engineer', 'Hard'),
('Which architecture does NOT use recurrence?', 'mcq', 'A. RNN|B. LSTM|C. Transformer|D. GRU', 'C', 'AI Engineer', 'Hard'),
('Which loss is used in WGANs?', 'mcq', 'A. Binary Cross Entropy|B. Wasserstein Loss|C. Hinge Loss|D. Smooth L1 Loss', 'B', 'AI Engineer', 'Hard'),
('Which NLP model is based on attention mechanisms?', 'mcq', 'A. Word2Vec|B. RNN|C. BERT|D. LSTM', 'C', 'AI Engineer', 'Hard'),
('What does BLEU score evaluate?', 'mcq', 'A. Classification accuracy|B. Sentiment polarity|C. Translation quality|D. Syntax errors', 'C', 'AI Engineer', 'Hard'),
('Which algorithm works by maximizing the margin between classes?', 'mcq', 'A. SVM|B. CNN|C. KNN|D. LDA', 'A', 'AI Engineer', 'Hard'),
('What is label smoothing?', 'mcq', 'A. Removing labels|B. Adding noise to labels|C. Making labels uniform|D. Using soft targets', 'D', 'AI Engineer', 'Hard'),
('Which evaluation metric is best for GANs?', 'mcq', 'A. FID|B. RMSE|C. MAE|D. F1 Score', 'A', 'AI Engineer', 'Hard'),
('Which model is good for long document summarization?', 'mcq', 'A. GPT-2|B. LSTM|C. BERTSum|D. CNN', 'C', 'AI Engineer', 'Hard'),
('Which of the following is a self-supervised learning technique?', 'mcq', 'A. Decision Tree|B. GPT|C. Random Forest|D. Logistic Regression', 'B', 'AI Engineer', 'Hard'),
('What is the key idea behind contrastive learning?', 'mcq', 'A. Boost classification|B. Predict exact labels|C. Learn from similarity|D. Clustering', 'C', 'AI Engineer', 'Hard'),
('What is a common challenge in multi-modal AI?', 'mcq', 'A. Image classification|B. Overfitting|C. Modality alignment|D. Gradient explosion', 'C', 'AI Engineer', 'Hard'),
('Which technique improves interpretability in ML models?', 'mcq', 'A. LIME|B. Dropout|C. Pruning|D. Adam', 'A', 'AI Engineer', 'Hard'),
('Which NLP model uses sentence embeddings for search?', 'mcq', 'A. GPT|B. Word2Vec|C. SBERT|D. LDA', 'C', 'AI Engineer', 'Hard'),
('Which strategy helps when data is limited?', 'mcq', 'A. Data augmentation|B. Dropout|C. Batch Norm|D. PCA', 'A', 'AI Engineer', 'Hard'),
('What is the role of cosine similarity in NLP?', 'mcq', 'A. Compute loss|B. Compare vectors|C. Normalize weights|D. Train models', 'B', 'AI Engineer', 'Hard'),
('Which is a common benchmark dataset for image classification?', 'mcq', 'A. MNIST|B. COCO|C. SQuAD|D. LibriSpeech', 'A', 'AI Engineer', 'Hard');
